---
- name: Enforce single Google Chrome installation (GNOME-safe)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    allowed_browser: google-chrome-stable

  #####################################################################
  # PREFLIGHT DETECTION
  #####################################################################
  tasks:

    - name: Preflight | Detect installed APT browsers
      shell: dpkg -l | egrep -i "chrome|chromium" || true
      register: apt_browsers
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Preflight | Detect snap browsers
      shell: snap list 2>/dev/null | egrep -i "chrome|chromium" || true
      register: snap_browsers
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Preflight | Detect flatpak browsers
      shell: flatpak list 2>/dev/null | egrep -i "chrome|chromium" || true
      register: flatpak_browsers
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Preflight report
      debug:
        msg:
          - "APT: {{ apt_browsers.stdout | default('none') }}"
          - "Snap: {{ snap_browsers.stdout | default('none') }}"
          - "Flatpak: {{ flatpak_browsers.stdout | default('none') }}"

  #####################################################################
  # ENFORCE SINGLE-BROWSER POLICY
  #####################################################################

    - name: Remove Chromium (APT)
      apt:
        name:
          - chromium
          - chromium-browser
        state: absent
        purge: yes
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Chrome beta / unstable
      apt:
        name:
          - google-chrome-beta
          - google-chrome-unstable
        state: absent
        purge: yes
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Chromium snap
      command: snap remove chromium
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Chromium flatpak
      command: flatpak uninstall -y org.chromium.Chromium
      ignore_errors: yes
      when: ansible_os_family == "Debian"

  #####################################################################
  # DESKTOP & APP CLEANUP (CRITICAL FIX)
  #####################################################################

    - name: Remove duplicate Chrome desktop application (GNOME)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/share/applications/com.google.Chrome.desktop
        - /home/*/.local/share/applications/com.google.Chrome.desktop
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove leftover Chromium desktop entries
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/share/applications/chromium-browser.desktop
        - /usr/share/applications/chromium.desktop
        - /var/lib/snapd/desktop/applications/chromium_chromium.desktop
      ignore_errors: yes
      when: ansible_os_family == "Debian"

  #####################################################################
  # INSTALL APPROVED BROWSER
  #####################################################################

    - name: Add Google Chrome GPG key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Google Chrome (approved browser)
      apt:
        name: "{{ allowed_browser }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

  #####################################################################
  # GNOME FAVORITES FIX (PER-USER)
  #####################################################################

    - name: Remove duplicate Chrome from GNOME favorites
      become: false
      shell: |
        gsettings set org.gnome.shell favorite-apps \
        "$(gsettings get org.gnome.shell favorite-apps | \
        sed "s/'com.google.Chrome.desktop', //; s/, 'com.google.Chrome.desktop'//; s/'com.google.Chrome.desktop'//")"
      environment:
        DISPLAY: ":0"
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_uid }}"
      when:
        - ansible_env.XDG_CURRENT_DESKTOP is defined
        - "'GNOME'" in ansible_env.XDG_CURRENT_DESKTOP
      ignore_errors: yes

  #####################################################################
  # FINALIZE
  #####################################################################

    - name: Rebuild desktop application database
      command: update-desktop-database
      ignore_errors: yes
      when: ansible_os_family == "Debian"

